### ISSUE TITLE
Felaqua doesn't update if no pet detected.

### ISSUE THREAD

**Issue by blair287** [benleb/surepetcare#6]
Think this might be a bug 

But sometimes the felaqua says XX water has been removed because it didn't see a microchip.

The Dev in chrome shows a log with a new actual weight and change however the HA entity doesn't update.

![Screenshot_20210510-180919](https://user-images.githubusercontent.com/44187409/117698190-58198400-b1bb-11eb-87a3-84f1b3d09c1f.png)
![Screenshot_20210510-180941~2](https://user-images.githubusercontent.com/44187409/117698204-5cde3800-b1bb-11eb-8a47-fd8fb5f10f5b.png)
![PXL_20210510_170935387~2](https://user-images.githubusercontent.com/44187409/117698211-6071bf00-b1bb-11eb-9581-61627f835a42.jpg)

**Comment by benleb** [comment]
hm how is this related to #4? or did you forget about? :D :D I have a fix in the pipeline to use the `actual_weight` field if available - would that be correct from your view?

**Comment by blair287** [comment]
> hm how is this related to #4? or did you forget about? :D :D I have a fix in the pipeline to use the `actual_weight` field if available - would that be correct from your view?

Ignore 4 I think might just been a funny 5 minutes.

Current weight is there all the time from what I can see if no pet or pet, current weight is correct

**Comment by benleb** [comment]
update pushed, but with the actual_weight... if actual_weight is wrong, tell me and we switch to the current_weight ⚖️ (but not today ✌️  editor closed for today :D)

**Comment by blair287** [comment]
> update pushed, but with the actual_weight... if actual_weight is wrong, tell me and we switch to the current_weight ⚖️ (but not today ✌️ editor closed for today :D)

updated doesnt load integration has an error.

`Logger: homeassistant.setup
Source: setup.py:310
First occurred: 20:05:20 (1 occurrences)
Last logged: 20:05:20

Unable to prepare setup for platform surepetcarebeta.sensor: Platform not found (cannot import name 'FeederBowl' from 'surepy.entities.devices' (/usr/local/lib/python3.8/site-packages/surepy/entities/devices.py)).`

No problem good work :) Looks like error maybe need surepy updated but no idea how to update that in HA.

**Comment by benleb** [comment]
ah fuck, forgot to change the required version of surepy in the manifest, should work now :)

**Comment by blair287** [comment]
> ah fuck, forgot to change the required version of surepy in the manifest, should work now :)

Yep working will monitor next time it doesn't know which pet drank if it still goes down.

Cheers

**Comment by blair287** [comment]
> ah fuck, forgot to change the required version of surepy in the manifest, should work now :)

Still not updating when it doesn't see pet.

Had 19ml removed at 19:19 but HA shows no change for 7 hours.

**Comment by blair287** [comment]
Tested a few more times working perfect when it knows who drank but doesn't update for when it says so much has been removed.

Any way to get round this? The notifications I see in the Dev tools for chrome shows it generates a notification and current weight updates.

**Comment by benleb** [comment]
Im on it :) cant promise I will finish it today but it will come really soon :)

**Comment by benleb** [comment]
@blair287, I think it should show always the correct values ;) 

but! :D I also implemented this config flow/click-to-config **** so gl updating 😅 maybe you have to delete the config enter from your configuration.yaml and re-add it via the "integrations" menu... (hint: top field is sure petcare username/mail and the lower one the password :D)

**Comment by blair287** [comment]
> @blair287, I think it should show always the correct values ;)
> 
> but! :D I also implemented this config flow/click-to-config **** so gl updating 😅 maybe you have to delete the config enter from your configuration.yaml and re-add it via the "integrations" menu... (hint: top field is sure petcare username/mail and the lower one the password :D)

I managed to update, awesome work on making it able to be added via the UI! Was gonna be my next suggestion 🤣

I'll keep an eye out and see if it works with no pet detected.

Looks really good now would you be able to use custom icons if I sent you the SVG images for the entities like feeder, flap, hub and felaqua?

**Comment by blair287** [comment]
@benleb 

It's working! It saw the change even with no pet identified! Great work 👌

**Comment by benleb** [comment]
![2021-05-16 09 15 49](https://user-images.githubusercontent.com/512997/118388908-6f2afc80-b627-11eb-85d6-0f219f0fcb43.gif)
